### ISSUE TITLE
Panic in deletion_controller

### ISSUE THREAD

**Issue by robbyt** [heptio/ark#497]
GCP is currently having some issues with networking in one of my regions. This seems to have caused Ark to panic. Here's the stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1d0 pc=0x10cac15]

goroutine 2724 [running]:
github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111 panic(0x182f800, 0x27a5570)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/heptio/ark/pkg/controller.(*backupDeletionController).processRequest(0xc420098790, 0xc4210cc3c0, 0xc4210cc280, 0xc4210cc280)
	/go/src/github.com/heptio/ark/pkg/controller/backup_deletion_controller.go:220 +0x545
```

**Comment by ncdc** [comment]
Thanks for reporting this. We’ll investigate tomorrow.

**Comment by ncdc** [comment]
I see what the problem is. We're checking for an error but not returning early when we encounter one: https://github.com/heptio/ark/blob/5d74a92cf1ddd4288ef4de49ac16649669636adc/pkg/controller/backup_deletion_controller.go#L212-L214.

And then when we proceed past that error:

https://github.com/heptio/ark/blob/5d74a92cf1ddd4288ef4de49ac16649669636adc/pkg/controller/backup_deletion_controller.go#L220

`backup` is `nil`.

We'll get a fix in for this. I'm also curious why the patch failed - do you have the ark pod logs from that time?
