### ISSUE TITLE
BUG: Panic when buckets no longer available

### ISSUE THREAD

**Issue by pms1969** [heptio/ark#618]
Hi,  I recently did a bit of work with a plugin, and probably mullered something properly.  However when I came to start afresh, the Ark pod had restarted, and I was getting the following error:

```bash
.
.
.
time="2018-06-28T11:21:12Z" level=info msg="Caches are synced" logSource="pkg/controller/download_request_controller.go:129"                                                                   
time="2018-06-28T11:21:12Z" level=info msg="Removing PV snapshots" backup=prod-tools4 controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:232" name=prod-tools4-
ktl9q namespace=heptio-ark                                                                                                                                                                     
time="2018-06-28T11:21:12Z" level=info msg="Removing restic snapshots" backup=prod-tools4 controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:241" name=prod-too
ls4-ktl9q namespace=heptio-ark                                                                                                                                                                 
E0628 11:21:12.306986       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)          
/go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72                                                                                                        
/go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65                                                                                                        
/go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51                                                                                                        
/usr/local/go/src/runtime/asm_amd64.s:573                                                                                                                                                      
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/go/src/github.com/heptio/ark/pkg/controller/backup_deletion_controller.go:246
/go/src/github.com/heptio/ark/pkg/controller/backup_deletion_controller.go:99
/go/src/github.com/heptio/ark/pkg/controller/backup_deletion_controller.go:138
/go/src/github.com/heptio/ark/pkg/controller/backup_deletion_controller.go:92
/go/src/github.com/heptio/ark/pkg/controller/generic_controller.go:128
/go/src/github.com/heptio/ark/pkg/controller/generic_controller.go:115
/go/src/github.com/heptio/ark/pkg/controller/generic_controller.go:89
/go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/go/src/github.com/heptio/ark/pkg/controller/generic_controller.go:89
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x10c2d73]
goroutine 307 [running]:
github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107                                                                                        
panic(0x17e9200, 0x27d95b0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/heptio/ark/pkg/controller.(*backupDeletionController).processRequest(0xc4203dbc70, 0xc4208fc140, 0xc4208fc000, 0xc4208fc000)                                                       
        /go/src/github.com/heptio/ark/pkg/controller/backup_deletion_controller.go:246 +0x9c3
github.com/heptio/ark/pkg/controller.(*backupDeletionController).(github.com/heptio/ark/pkg/controller.processRequest)-fm(0xc4208fc000, 0xc4208fc000, 0x0)                                    
        /go/src/github.com/heptio/ark/pkg/controller/backup_deletion_controller.go:99 +0x34
github.com/heptio/ark/pkg/controller.(*backupDeletionController).processQueueItem(0xc4203dbc70, 0xc42032d900, 0x1c, 0x18, 0xc42087edb8)                                                       
        /go/src/github.com/heptio/ark/pkg/controller/backup_deletion_controller.go:138 +0x260
github.com/heptio/ark/pkg/controller.(*backupDeletionController).(github.com/heptio/ark/pkg/controller.processQueueItem)-fm(0xc42032d900, 0x1c, 0xc4205b2d20, 0x16cc3a0)                      
        /go/src/github.com/heptio/ark/pkg/controller/backup_deletion_controller.go:92 +0x3e
github.com/heptio/ark/pkg/controller.(*genericController).processNextWorkItem(0xc4202bf2c0, 0xc4200be800)                                                                                     
        /go/src/github.com/heptio/ark/pkg/controller/generic_controller.go:128 +0xd1
github.com/heptio/ark/pkg/controller.(*genericController).runWorker(0xc4202bf2c0)
        /go/src/github.com/heptio/ark/pkg/controller/generic_controller.go:115 +0x2b
github.com/heptio/ark/pkg/controller.(*genericController).(github.com/heptio/ark/pkg/controller.runWorker)-fm()                                                                               
        /go/src/github.com/heptio/ark/pkg/controller/generic_controller.go:89 +0x2a
github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4205947a0)
        /go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54                                                                                              
github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420643fa0, 0x3b9aca00, 0x0, 0x7fec8f2c8401, 0xc42008a420)                                                       
        /go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd                                                                                              
github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4205947a0, 0x3b9aca00, 0xc42008a420)                                                                                  
        /go/src/github.com/heptio/ark/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d                                                                                               
github.com/heptio/ark/pkg/controller.(*genericController).Run.func2(0xc4202bf2c0, 0x1c450e0, 0xc420331400, 0xc420328070)                                                                      
        /go/src/github.com/heptio/ark/pkg/controller/generic_controller.go:89 +0x68
created by github.com/heptio/ark/pkg/controller.(*genericController).Run
        /go/src/github.com/heptio/ark/pkg/controller/generic_controller.go:88 +0x2f6
```

I had removed the s3 bucket that was being used to backup the restic volumes, so this could be related.

Additionally, the pod itself failed to restart after that panic.  I'd expect to see it in a never ending  loop of CrashBackupLoop, but not so.

To resolve the issue, I just removed the backup requests with the following:
```bash
k -n heptio-ark delete DeleteBackupRequest prod-tools4-fsfv2
```

**Comment by ncdc** [comment]
The panic occurred here, where we weren't checking if `c.resticMgr` was nil:

https://github.com/heptio/ark/blob/11c3837f9b8e2a4dbbb847e9c3a3bc8afa645a76/pkg/controller/backup_deletion_controller.go#L246

This has been fixed in master:

https://github.com/heptio/ark/blob/51298f84cccaa28d78f013e8096d863f2e820d7f/pkg/controller/backup_deletion_controller.go#L307
